#!/usr/bin/env python
from snake_track.args import get_args
from snake_track.bucket_upload import upload_files_to_s3_bucket

def main():
    args = get_args()
    if 'bucketName' in args:  # this is a bucket uplaod
        
        

if __name__ == '__main__':
    main()